### ISSUE TITLE
keyboard.isEnabled didn't Trigger observe function

### ISSUE THREAD

**Issue by emre-yilmaz** [morizotter/KeyboardObserver#14]
I have UITextField and UIButton. I'm texing to the UItextfield and then pressing the submit button. but didn't trigger kerboard observe func. 

Share button action :

      @IBAction func shareButtonPressed(_ sender: UIButton){
        shareButton.isEnabled = false
        self.keyboard.isEnabled = !self.keyboard.isEnabled 
        }

Have any solution?

**Comment by morizotter** [comment]
KeyboardObserver just observes the keyboard state changes. `isEnabled` changes whether observe or not.

I think you have to do is to resign textfield's responder.

Something like:

```swift
@IBAction func shareButtonPressed(_ sender: UIButton){
    shareButton.isEnabled = false
    // self.keyboard.isEnabled = !self.keyboard.isEnabled 
    textField.resignFirstResponder()
    }
```

**Comment by emre-yilmaz** [comment]
Thanks your solution. It's running now 👍
