### ISSUE TITLE
Failed to push 1.0.0 to cocoapods.

### ISSUE THREAD

**Issue by morizotter** [morizotter/KeyboardObserver#8]
Currently, master branch's swift verison is 3. However, I cannot succeed to push project to Cocoapods so you can not use it with Cocoapods.

I think this relates to the cocoapods bug.

https://github.com/CocoaPods/CocoaPods/issues/5805

This issue was closed but the problem is maybe not solved in the 1.1.0.rc.1 release.

I'm using 
- Xcode 8 GM
- 1.1.0.rc.1.

**Comment by morizotter** [comment]
This relates to https://github.com/morizotter/KeyboardObserver/pull/7 .

**Comment by morizotter** [comment]
I put the pre-release tag to 1.0.0 release. I think you can use it with Carthage now but not with Cocoapods.

**Comment by ossmalpha** [comment]
Why is this not working with Swift 3 on Xcode 8? I can see that the master branch was updated, but I still get a lot of errors.

**Comment by morizotter** [comment]
I could build with no errors. What errors did you get?

**Comment by morizotter** [comment]
Release for Swift3: https://github.com/morizotter/KeyboardObserver/releases/tag/1.0.1
Release for Swift2.3: https://github.com/morizotter/KeyboardObserver/releases/tag/0.5.1

**Comment by morizotter** [comment]
Cocoapods have already been supported.
